version: '3'

services:
  api_user:
    image: node:18.17.0-bullseye
    container_name: api_user
    ports: [ "3000:3000" ]
    volumes: [ "./api-user:/app" ]
    working_dir: /app
    command: >
      bash -c 'npm install -g @nestjs/cli@^9.0.0 && npm run start:dev'
  api_emails:
    image: node:18.17.0-bullseye
    container_name: api_emails
    ports: [ "3001:3001" ]
    volumes: [ "./api-emails:/app" ]
    working_dir: /app
    command: >
      bash -c 'npm install -g @nestjs/cli@^9.0.0 && npm run start:dev'
  user_database:
    image: mongo:6.0.13-jammy
    container_name: user_database
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users
    command: mongod --quiet --logpath /dev/null
      
